# Generated by Django 4.1.2 on 2022-10-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0002_alter_pais_options_alter_pais_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionario',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.pais'),
        ),
    ]
