# Generated by Django 4.1.2 on 2022-10-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0003_alter_concesionario_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concesionario',
            options={'verbose_name': 'Concesionario', 'verbose_name_plural': 'Concesionarios'},
        ),
        migrations.AlterModelTable(
            name='concesionario',
            table='concesionario',
        ),
    ]
