# Generated by Django 4.1.2 on 2022-10-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0004_alter_concesionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('-', '--')], default='-', max_length=1),
        ),
    ]
