# Generated by Django 4.1.2 on 2022-10-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0006_administrador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='idConcesionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario', verbose_name='Concesionario'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='paisOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosapp.pais', verbose_name='Pais de origen'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tfno',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
    ]
