# Generated by Django 4.1.2 on 2022-10-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0010_alter_administrador_idconcesionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='idConcesionario',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
