# Generated by Django 4.1.2 on 2022-10-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0011_alter_administrador_idconcesionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='idConcesionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario'),
        ),
    ]
