# Generated by Django 4.1.2 on 2022-10-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0013_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autosapp.persona')),
                ('idConcesionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario')),
                ('paisOrigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.pais')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
            bases=('autosapp.persona',),
        ),
    ]
