# Generated by Django 4.1.2 on 2022-10-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0014_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('year', models.DateField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('-', '--')], default='-', max_length=1)),
                ('categoria', models.CharField(choices=[('p', 'Pesado'), ('M', 'Ligero'), ('E', 'Especiales'), ('A', 'Agricolas'), ('-', '--')], default='-', max_length=1)),
                ('tipoV', models.CharField(max_length=50)),
                ('precioCompra', models.IntegerField()),
                ('idConcesionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculo',
            },
        ),
    ]
