# Generated by Django 4.1.2 on 2022-10-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0015_alter_cliente_table_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='idConcesionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario', verbose_name='Concesionario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precioCompra',
            field=models.IntegerField(verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipoV',
            field=models.CharField(max_length=50, verbose_name='Tipo de vehiculo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioVehiculo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosapp.cliente', verbose_name='Comprador')),
                ('idVehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.vehiculo', verbose_name='Vehiculo')),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosapp.empleado', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Vetas',
                'db_table': 'venta',
            },
        ),
    ]
