# Generated by Django 4.1.2 on 2022-10-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0016_alter_vehiculo_idconcesionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.CreateModel(
            name='Provehedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autosapp.persona')),
                ('ciudad', models.CharField(max_length=25)),
                ('idVehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.vehiculo', verbose_name='Vehiculo')),
                ('paisOrigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.pais')),
            ],
            options={
                'verbose_name': 'Provehedor',
                'verbose_name_plural': 'Provehedores',
                'db_table': 'provehedor',
            },
            bases=('autosapp.persona',),
        ),
    ]
