# Generated by Django 4.1.2 on 2022-10-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosapp', '0017_alter_venta_options_provehedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='autosapp'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idConcesionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.concesionario', verbose_name='Concesionario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='paisOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autosapp.pais', verbose_name='Pais de origen'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Indefinido'), ('-', '--')], default='-', max_length=1),
        ),
    ]
